title: Swarit Shukla
description: AI engineer building machine learning systems and real world AI applications
url: "https://swaritshukla.me"

# Exclude files from being built
exclude:
  - README.md

future: true
timezone: Asia/Kolkata

plugins:
  - jekyll-sitemap
